"""empty message

Revision ID: 38fd1dec414f
Revises: 539f6c6f3e7f
Create Date: 2021-07-02 19:30:50.671296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fd1dec414f'
down_revision = '539f6c6f3e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ner_tag_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ner_tag_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
