"""empty message

Revision ID: f2f61d2d1fb7
Revises: 2c32abc9392a
Create Date: 2021-07-07 20:46:24.200644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f61d2d1fb7'
down_revision = '2c32abc9392a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('upload_date')
        batch_op.drop_column('file_name')
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
